# docker-compose.yml
services:
  backend:
    build: ./server
    image: loisekk/openml-flow-backend:latest
    container_name: openmlpipe-backend
    ports:
      - "3001:3001"
    volumes:
      # Mount directories, not files. This prevents the Windows mount bug.
      - ./server/uploads:/app/uploads
      - ./server/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./client
    image: loisekk/openml-flow-frontend:latest
    container_name: openmlpipe-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
